<h1>Liste des Utilisateurs</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a href="#">Voir</a>
                <a href="#">Modifier</a>
                <a href="#">Supprimer</a>
            </td>
        </tr>
    </tbody>
</table>